name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: NiceAshin/my_blog@main
        with:
          target_branch: gh-pages
          build_dir: public
          GITHUB_TOKEN: ${{ secrets.MYBLOGSECRET }}

